version: "3"
services:
  api:
    container_name: "kanboom-container"
    build: .
    volumes:
      - "./app:/code/app"
    networks:
      - mynetwork
    ports:
      - "80:8000"
networks:
  mynetwork:
    driver: bridge
